staysafeapp/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
]

staysafeapp/display/urls.py
from django.urls import path
from . import views

app_name = 'display'
urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('video_feed/', views.video_feed, name='video_feed'),
    path('toggle_camera/', views.toggle_camera, name='toggle_camera'),
]

staysafeapp/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'
urlpatterns = [
    path('', views.employee_list, name='employee_list'),
    path('detail/<str:sicil_no>/', views.employee_detail, name='employee_detail'),
    path('create/', views.employee_create, name='employee_create'),
    path('edit/<str:sicil_no>/', views.employee_edit, name='employee_edit'),
    path('delete/<str:sicil_no>/', views.employee_delete, name='employee_delete'),
]

staysafeapp/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.report_list, name='report_list'),
    path('report/<int:report_id>/', views.report_detail, name='report_detail'),
    path('report/<int:report_id>/delete/', views.report_delete, name='report_delete'),
] 

staysafeapp/staysafeapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

def redirect_to_home(request):
    return redirect('display/')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_home, name='home'),  # Ana sayfa yönlendirmesi
    path('display/', include('display.urls')),
    path('employees/', include('employees.urls')),
    path('reports/', include('reports.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staysafeapp/templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">StaySafe</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'display:home' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'display:index' %}">Kamera İzleme</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:report_list' %}">Raporlar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'employees:employee_list' %}">Çalışanlar</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-1">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:user_register' %}">Kayıt Ol</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:user_login' %}">Giriş Yap</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:user_logout' %}">Çıkış Yap</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div style="padding-top: 60px;"></div>